import type { Metadata } from 'next'
import Link from 'next/link'
import { Shield, Zap, Database, RefreshCw } from 'lucide-react'

export const metadata: Metadata = {
  title: 'About Laptick — How It Works',
  description:
    'How Laptick recommends laptops: AI-powered analysis of real hardware specs, not marketing copy. Learn about our methodology and how we keep data fresh.',
}

export default function AboutPage() {
  return (
    <article className="mx-auto max-w-3xl px-4 py-10 space-y-10">
      <div>
        <h1 className="text-3xl font-bold mb-3">How Laptick Works</h1>
        <p className="text-muted-foreground">
          A transparent explanation of our recommendation methodology, data sources, and cost model.
        </p>
      </div>

      <section className="space-y-4">
        <h2 className="text-xl font-bold">The Problem We Solve</h2>
        <p className="text-muted-foreground leading-relaxed">
          Most laptop review sites are written for enthusiasts who already know what "RTX 4060" or
          "H-series processor" means. Amazon and Flipkart listings are stuffed with specs but give
          you no idea which ones actually matter for your work.
        </p>
        <p className="text-muted-foreground leading-relaxed">
          Laptick bridges this gap. We take your answers to 5 simple questions and explain —
          in plain English — exactly why a specific laptop's specs make it right for your use case.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold">How Recommendations Are Generated</h2>
        <div className="grid gap-4 sm:grid-cols-2">
          {[
            {
              icon: Database,
              title: '1. Smart Pre-filtering',
              desc: 'We first filter our database by your budget, OS preference, and use-case tags. You never pay for Claude to analyse laptops outside your price range.',
            },
            {
              icon: Zap,
              title: '2. AI Analysis',
              desc: 'Claude (Anthropic\'s AI) analyses 10–15 pre-filtered laptops against your specific needs. It\'s trained on hardware knowledge including GPU TGP, CPU series performance, and display specifications.',
            },
            {
              icon: Shield,
              title: '3. Expert Explanations',
              desc: 'Every recommendation includes a plain-English explanation of WHY — mentioning specific specs and their real-world impact on your workflow.',
            },
            {
              icon: RefreshCw,
              title: '4. Weekly Updates',
              desc: 'Every Monday, an automated agent searches for new laptop releases and price changes, updating our database. Cached results are cleared so you always get current prices.',
            },
          ].map(({ icon: Icon, title, desc }) => (
            <div key={title} className="rounded-lg border border-border/50 p-5 space-y-2">
              <Icon className="h-5 w-5 text-blue-400" />
              <p className="font-semibold">{title}</p>
              <p className="text-sm text-muted-foreground">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold">Affiliate Disclosure</h2>
        <p className="text-muted-foreground leading-relaxed">
          Laptick participates in the Amazon Associates programme. When you click "Buy on
          Amazon" and complete a purchase, we earn a small commission at no extra cost to you.
        </p>
        <p className="text-muted-foreground leading-relaxed">
          <strong className="text-foreground">This never influences our rankings.</strong> Our
          recommendations are generated by AI based solely on spec analysis. We include honest
          weaknesses for every laptop we recommend — including the #1 pick.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold">Data Freshness</h2>
        <p className="text-muted-foreground leading-relaxed">
          Laptop prices in India change frequently. Our database is updated every Monday via an
          automated agent that searches for new releases, price drops, and discontinued models.
          Prices shown are accurate as of the last Monday update.
        </p>
      </section>

      <div className="rounded-xl bg-blue-600/10 border border-blue-500/30 p-6 text-center space-y-3">
        <p className="font-semibold">Ready to find your laptop?</p>
        <Link
          href="/"
          className="inline-block rounded-lg bg-blue-600 px-6 py-2.5 text-sm font-medium text-white hover:bg-blue-700 transition-colors"
        >
          Get My Recommendation →
        </Link>
      </div>
    </article>
  )
}
