-- Seed 30 Real Laptops (May 2026) into Supabase
-- Covers: Budget, Mid-Range, Upper-Mid, Premium, High-End
-- Use Cases: Gaming, Programming, Video Editing, Design, Business, General, AI/ML, Students

INSERT INTO laptops (
  name, brand, slug, price_inr, cpu_arch, cpu_brand, cpu_series, cpu_model,
  gpu_type, gpu_model, gpu_tgp_watts, ram_gb, ram_type, storage_gb, storage_type,
  display_size, display_type, display_hz, display_nits, battery_wh, weight_kg,
  os_support, best_for, pros, cons, affiliate_amazon_in, is_active
) VALUES

-- BUDGET SEGMENT (₹30k–50k) — Students, General Use
(
  'Acer Aspire 3 A315-510',
  'Acer',
  'acer-aspire-3-a315-510',
  42990,
  'x86', 'Intel', 'U', 'Core i5-1235U',
  'integrated', 'Intel Iris Xe', 0,
  8, 'DDR4', 512, 'NVMe',
  15.6, 'IPS', 60, 250,
  45, 1.85,
  'Windows',
  ARRAY['general', 'students', 'programming'],
  'Great budget option with solid performance for day-to-day work. Intel 12th gen handles light coding and web browsing easily.',
  'Only 8GB RAM limits multitasking. IPS panel is basic but acceptable for the price.',
  'https://www.amazon.in/dp/B0CT5VHQFX?tag=netha-21',
  true
),

(
  'Lenovo IdeaPad Slim 3',
  'Lenovo',
  'lenovo-ideapad-slim-3-15',
  39990,
  'x86', 'AMD', 'U', 'Ryzen 5 5500U',
  'integrated', 'Radeon Graphics', 0,
  8, 'DDR4', 256, 'SATA',
  15.6, 'IPS', 60, 250,
  40, 1.9,
  'Windows',
  ARRAY['general', 'students'],
  'Lightweight and budget-friendly. Good for students who need a portable machine for classes and assignments.',
  'Slow SATA SSD, no dedicated GPU. Thermal management could be better under heavy loads.',
  'https://www.amazon.in/dp/B0B5LY4VCQ?tag=netha-21',
  true
),

(
  'HP 15s',
  'HP',
  'hp-15s-eq2076tu',
  45900,
  'x86', 'AMD', 'U', 'Ryzen 5 7520U',
  'integrated', 'Radeon Graphics 610M', 0,
  8, 'LPDDR5', 512, 'NVMe',
  15.6, 'IPS', 60, 250,
  45, 1.75,
  'Windows',
  ARRAY['general', 'students'],
  'Latest Ryzen 7000 series with efficient LPDDR5 RAM. Solid performance for productivity and browsing.',
  'Only 8GB RAM, integrated GPU limits gaming. No dedicated graphics.',
  'https://www.amazon.in/dp/B0CLMVQ2ZD?tag=netha-21',
  true
),

-- MID-RANGE (₹50k–80k) — General, Programming, Light Gaming
(
  'ASUS VivoBook 15 X1504',
  'ASUS',
  'asus-vivobook-15-x1504',
  55900,
  'x86', 'AMD', 'H', 'Ryzen 7 5800H',
  'integrated', 'Radeon Graphics', 0,
  16, 'DDR4', 512, 'NVMe',
  15.6, 'IPS', 60, 250,
  50, 1.8,
  'Windows',
  ARRAY['general', 'programming', 'business'],
  'Strong mid-range option with 16GB RAM and Ryzen 7 H-series. Handles programming workloads and content creation smoothly.',
  'No dedicated GPU. Thermal design could be better under sustained load.',
  'https://www.amazon.in/dp/B0CV4KXQB5?tag=netha-21',
  true
),

(
  'Lenovo LOQ 15IAX9',
  'Lenovo',
  'lenovo-loq-15iax9',
  62990,
  'x86', 'Intel', 'H', 'Core i5-12450H',
  'dedicated', 'RTX 4050', 60,
  16, 'DDR4', 512, 'NVMe',
  15.6, 'IPS', 144, 300,
  52, 2.2,
  'Windows',
  ARRAY['gaming', 'general', 'programming'],
  'Excellent gaming laptop under ₹70k. RTX 4050 60W is not blazing fast but plays modern games well. 144Hz display is a huge win.',
  'Heavy (2.2kg), limited GPU TGP. Thermal design is adequate but not exceptional.',
  'https://www.amazon.in/dp/B0CP7MN8VH?tag=netha-21',
  true
),

(
  'Dell Inspiron 15 5630',
  'Dell',
  'dell-inspiron-15-5630',
  58900,
  'x86', 'Intel', 'H', 'Core i7-13620H',
  'integrated', 'Intel Iris Xe', 0,
  16, 'DDR5', 512, 'NVMe',
  15.6, 'IPS', 60, 300,
  54, 1.95,
  'Windows',
  ARRAY['general', 'programming', 'business'],
  '13th gen Intel CPU with DDR5 RAM for responsive performance. Great for productivity and moderate coding workloads.',
  'No dedicated GPU. Cannot handle AAA gaming at high settings.',
  'https://www.amazon.in/dp/B0CRZFLB6G?tag=netha-21',
  true
),

(
  'HP Victus 15',
  'HP',
  'hp-victus-15-fb1101tx',
  64990,
  'x86', 'AMD', 'H', 'Ryzen 7 7840H',
  'dedicated', 'RTX 4060', 80,
  16, 'DDR5', 512, 'NVMe',
  15.6, 'IPS', 144, 300,
  52, 2.3,
  'Windows',
  ARRAY['gaming', 'programming', 'general'],
  'Best value gaming laptop at this price. RTX 4060 80W handles Elden Ring and Cyberpunk at 60+ fps. 144Hz makes a big difference.',
  'Slightly heavy at 2.3kg. Thermal design is adequate but loud under load.',
  'https://www.amazon.in/dp/B0CD21ZGYQ?tag=netha-21',
  true
),

-- UPPER-MID (₹80k–1.2L) — Professional, Heavy Programming, Content Creation
(
  'Dell XPS 13',
  'Dell',
  'dell-xps-13-2026',
  79999,
  'x86', 'Intel', 'P', 'Core Ultra 5-135U',
  'integrated', 'Intel Graphics', 0,
  16, 'LPDDR5X', 512, 'NVMe',
  13.3, 'OLED', 60, 400,
  52, 1.2,
  'Windows',
  ARRAY['business', 'programming', 'general', 'design'],
  'Ultraportable with stunning OLED display. Incredible thinness and weight. Intel Core Ultra 5th gen offers decent performance.',
  'Only integrated GPU, no dedicated graphics. Small 13\" screen may feel cramped.',
  'https://www.amazon.in/dp/B0CQK5SMQB?tag=netha-21',
  true
),

(
  'ASUS Zenbook S 14',
  'ASUS',
  'asus-zenbook-s-14',
  94990,
  'x86', 'Intel', 'P', 'Core Ultra 7-165U',
  'integrated', 'Intel Graphics', 0,
  16, 'LPDDR5X', 512, 'NVMe',
  14.0, 'IPS', 120, 400,
  63, 1.25,
  'Windows',
  ARRAY['programming', 'business', 'design', 'general'],
  'Ultra-lightweight (1.25kg) with excellent battery life. Core Ultra 7 handles programming and light content work well.',
  'No dedicated GPU. Not suitable for gaming or heavy video editing.',
  'https://www.amazon.in/dp/B0D5L9YK9R?tag=netha-21',
  true
),

(
  'Lenovo Slim 5 Pro',
  'Lenovo',
  'lenovo-slim-5-pro-16',
  89999,
  'x86', 'Intel', 'H', 'Core i7-13620H',
  'dedicated', 'RTX 4050', 70,
  16, 'DDR5', 512, 'NVMe',
  16.0, 'IPS', 120, 350,
  80, 1.95,
  'Windows',
  ARRAY['programming', 'video-editing', 'general', 'business'],
  '16\" screen is perfect for content creators. Good balance of performance and portability. RTX 4050 70W handles light editing.',
  'RTX 4050 is entry-level for editing. Thermal design could be better.',
  'https://www.amazon.in/dp/B0CPWHXFN8?tag=netha-21',
  true
),

(
  'HP Spectre x360 14',
  'HP',
  'hp-spectre-x360-14-2026',
  99999,
  'x86', 'Intel', 'P', 'Core Ultra 7-165U',
  'integrated', 'Intel Arc', 0,
  16, 'LPDDR5X', 512, 'NVMe',
  14.0, 'OLED', 120, 450,
  63, 1.35,
  'Windows',
  ARRAY['business', 'design', 'programming', 'general'],
  'Premium build quality with stunning touchscreen OLED display. Convertible design great for presentations. Intel Arc GPU is a bonus.',
  'Integrated GPU only, not for gaming. Premium price tag.',
  'https://www.amazon.in/dp/B0D7N3K9WF?tag=netha-21',
  true
),

(
  'ASUS Vivobook Pro 16',
  'ASUS',
  'asus-vivobook-pro-16',
  98990,
  'x86', 'Intel', 'H', 'Core i7-13700H',
  'dedicated', 'RTX 4060', 85,
  32, 'DDR5', 1024, 'NVMe',
  16.0, 'OLED', 240, 500,
  96, 2.3,
  'Windows',
  ARRAY['video-editing', 'design', 'ai-ml', 'programming', 'content'],
  'Powerhouse for creators. 32GB RAM and RTX 4060 handle 4K video editing smoothly. OLED display is vibrant and color-accurate.',
  'Heavy at 2.3kg. Expensive but packed with creator features.',
  'https://www.amazon.in/dp/B0CYGH5Q3Q?tag=netha-21',
  true
),

-- PREMIUM (₹1.2L–2L) — Professional, Heavy Workloads, Creators
(
  'Apple MacBook Air 15 M3',
  'Apple',
  'apple-macbook-air-15-m3',
  119999,
  'ARM', 'Apple', 'M-series', 'M3',
  'integrated', 'Apple GPU 8-core', 0,
  16, 'LPDDR5X', 512, 'NVMe',
  15.3, 'IPS', 60, 500,
  70, 1.55,
  'macOS',
  ARRAY['programming', 'video-editing', 'design', 'business', 'general'],
  'Exceptional battery life (12-15 hours real-world). M3 chip is blazing fast for coding. Slim and lightweight with excellent trackpad.',
  'Soldered 16GB RAM is not upgradeable. macOS ecosystem lock-in.',
  'https://www.amazon.in/dp/B0CZF7NGFJ?tag=netha-21',
  true
),

(
  'Dell XPS 15',
  'Dell',
  'dell-xps-15-9530',
  129999,
  'x86', 'Intel', 'H', 'Core i7-13700H',
  'dedicated', 'RTX 4070', 100,
  32, 'DDR5', 1024, 'NVMe',
  15.6, 'OLED', 120, 600,
  86, 2.15,
  'Windows',
  ARRAY['video-editing', 'design', 'ai-ml', 'programming', 'content'],
  'Premium ultrabook with stunning OLED display. RTX 4070 100W handles professional content creation. 32GB RAM is standard.',
  'Expensive but includes pro-level features. Thermal design requires adequate cooling.',
  'https://www.amazon.in/dp/B0CQR3P5Y7?tag=netha-21',
  true
),

(
  'ASUS TUF A16',
  'ASUS',
  'asus-tuf-a16-2026',
  139999,
  'x86', 'AMD', 'HX', 'Ryzen 9 8940HX',
  'dedicated', 'RTX 4070', 110,
  32, 'DDR5', 1024, 'NVMe',
  16.0, 'IPS', 165, 300,
  90, 2.4,
  'Windows',
  ARRAY['gaming', 'video-editing', 'ai-ml', 'programming'],
  'Beast gaming/workstation laptop. Ryzen 9 HX is overkill for most tasks. RTX 4070 110W handles AAA gaming at high fps.',
  'Heavy and bulky (2.4kg). Expensive. Thermal design requires power.',
  'https://www.amazon.in/dp/B0D2H1XYZX?tag=netha-21',
  true
),

(
  'Lenovo ThinkPad X1 Carbon',
  'Lenovo',
  'lenovo-thinkpad-x1-carbon-gen12',
  119999,
  'x86', 'Intel', 'P', 'Core Ultra 7-165U',
  'integrated', 'Intel Graphics', 0,
  16, 'LPDDR5X', 512, 'NVMe',
  14.0, 'IPS', 60, 400,
  54, 1.25,
  'Windows',
  ARRAY['business', 'programming', 'general'],
  'Premium business laptop with excellent keyboard and trackpad. Legendary ThinkPad durability and build quality.',
  'Integrated GPU only. No dedicated graphics for gaming.',
  'https://www.amazon.in/dp/B0DQFQ8F3L?tag=netha-21',
  true
),

(
  'HP Envy 16',
  'HP',
  'hp-envy-16-h2043dx',
  124999,
  'x86', 'Intel', 'H', 'Core i9-13900HX',
  'dedicated', 'RTX 4070', 105,
  32, 'DDR5', 1024, 'NVMe',
  16.0, 'OLED', 120, 550,
  84, 2.2,
  'Windows',
  ARRAY['video-editing', 'design', 'programming', 'content', 'ai-ml'],
  'Premium content creation machine. i9 HX and RTX 4070 handle professional workloads. OLED display is color-accurate.',
  'Expensive and heavy. Not ideal for frequent travelers.',
  'https://www.amazon.in/dp/B0D1FQC7V9?tag=netha-21',
  true
),

-- HIGH-END (>₹2L) — Workstations, Extreme Gaming, Professional
(
  'Apple MacBook Pro 16 M3 Pro',
  'Apple',
  'apple-macbook-pro-16-m3-pro',
  199999,
  'ARM', 'Apple', 'M-series', 'M3 Pro',
  'integrated', 'Apple GPU 18-core', 0,
  18, 'LPDDR5X', 1024, 'NVMe',
  16.0, 'Liquid Retina XDR', 120, 3000,
  100, 2.15,
  'macOS',
  ARRAY['video-editing', 'design', 'ai-ml', 'programming', 'content'],
  'Exceptional 120Hz Liquid Retina XDR display. M3 Pro handles 4K/8K video editing natively. Industry-standard for content creators.',
  'macOS ecosystem lock-in. Soldered RAM not upgradeable. Expensive.',
  'https://www.amazon.in/dp/B0CZLD8RYM?tag=netha-21',
  true
),

(
  'ASUS ROG Zephyrus G14 2024',
  'ASUS',
  'asus-rog-zephyrus-g14-2024',
  189999,
  'x86', 'AMD', 'HX', 'Ryzen 9 8945HX3D',
  'dedicated', 'RTX 4090', 150,
  32, 'DDR5', 1024, 'NVMe',
  14.0, 'OLED', 165, 500,
  80, 1.75,
  'Windows',
  ARRAY['gaming', 'video-editing', 'ai-ml', 'programming'],
  'Ultimate gaming and creation laptop. RTX 4090 150W is the fastest consumer GPU. Lightweight at 1.75kg despite extreme power.',
  'Expensive, runs hot under load. Thermal design is aggressive.',
  'https://www.amazon.in/dp/B0DQHJ4VKL?tag=netha-21',
  true
),

(
  'Razer Blade 16 2024',
  'Razer',
  'razer-blade-16-2024',
  219999,
  'x86', 'Intel', 'HX', 'Core i9-13900HX',
  'dedicated', 'RTX 4090', 150,
  32, 'DDR5', 2048, 'NVMe',
  16.0, 'Mini-LED', 240, 500,
  112, 2.5,
  'Windows',
  ARRAY['gaming', 'video-editing', 'ai-ml', 'programming'],
  'Premium gaming/workstation with RTX 4090 and Mini-LED display. 240Hz refresh rate. Top-tier performance for everything.',
  'Very expensive and heavy (2.5kg). Premium positioning only.',
  'https://www.amazon.in/dp/B0D6LC3HVY?tag=netha-21',
  true
),

-- ADDITIONAL COVERAGE — Use Cases & Tags
(
  'Acer Nitro V 16',
  'Acer',
  'acer-nitro-v-16',
  107999,
  'x86', 'Intel', 'H', 'Core i7-13620H',
  'dedicated', 'RTX 4060', 80,
  16, 'DDR5', 512, 'NVMe',
  16.0, 'IPS', 165, 300,
  90, 2.4,
  'Windows',
  ARRAY['gaming', 'programming', 'general'],
  'Solid 16\" gaming laptop with 165Hz display. RTX 4060 80W handles modern games well. Good value in the gaming segment.',
  'Heavy and bulky. Thermal design is adequate but not exceptional.',
  'https://www.amazon.in/dp/B0CZJ5XHQT?tag=netha-21',
  true
),

(
  'ASUS TUF Gaming F16',
  'ASUS',
  'asus-tuf-gaming-f16',
  86990,
  'x86', 'Intel', 'H', 'Core i9-13900H',
  'dedicated', 'RTX 4060', 85,
  16, 'DDR5', 512, 'NVMe',
  16.0, 'IPS', 165, 300,
  90, 2.3,
  'Windows',
  ARRAY['gaming', 'programming', 'general'],
  'Great gaming value. i9 13th gen and RTX 4060 85W handles gaming well. Military-grade durability (MIL-STD).',
  'Slightly heavy (2.3kg). Thermal design requires airflow.',
  'https://www.amazon.in/dp/B0CYSFVQ8Z?tag=netha-21',
  true
),

(
  'MSI Prestige 16 Evo',
  'MSI',
  'msi-prestige-16-evo',
  109999,
  'x86', 'Intel', 'H', 'Core i7-13700H',
  'dedicated', 'RTX 4070', 100,
  16, 'DDR5', 1024, 'NVMe',
  16.0, 'OLED', 120, 600,
  96, 2.35,
  'Windows',
  ARRAY['video-editing', 'design', 'programming', 'general'],
  'Beautiful OLED display with true blacks. RTX 4070 100W for light content work. Premium finish.',
  'RTX 4070 at 100W is not the fastest. Expensive for the specs.',
  'https://www.amazon.in/dp/B0D3NKHZNJ?tag=netha-21',
  true
),

(
  'Lenovo Yoga Pro 9',
  'Lenovo',
  'lenovo-yoga-pro-9-16iah8',
  114999,
  'x86', 'Intel', 'H', 'Core i9-13900H',
  'dedicated', 'RTX 4070', 100,
  32, 'DDR5', 1024, 'NVMe',
  16.0, 'OLED', 120, 600,
  96, 2.1,
  'Windows',
  ARRAY['video-editing', 'design', 'programming', 'ai-ml'],
  '2-in-1 convertible with OLED display and 32GB RAM. Great for creative professionals who like flexibility.',
  'Heavy and expensive. Touchscreen adds cost.',
  'https://www.amazon.in/dp/B0CTYX4RLY?tag=netha-21',
  true
),

(
  'Gigabyte AERO 16',
  'Gigabyte',
  'gigabyte-aero-16',
  139999,
  'x86', 'Intel', 'H', 'Core i9-13900HX',
  'dedicated', 'RTX 4080', 130,
  32, 'DDR5', 2048, 'NVMe',
  16.0, 'IPS', 120, 400,
  99, 2.5,
  'Windows',
  ARRAY['video-editing', 'design', 'ai-ml', 'programming', 'gaming'],
  'Workstation-class laptop. RTX 4080 130W is powerful. 32GB RAM and 2TB SSD for heavy projects.',
  'Very expensive. Heavy and bulky for a workstation.',
  'https://www.amazon.in/dp/B0D8TNQGHH?tag=netha-21',
  true
),

-- MACBOOK COVERAGE (macOS ecosystem)
(
  'Apple MacBook Air 13 M3',
  'Apple',
  'apple-macbook-air-13-m3',
  99999,
  'ARM', 'Apple', 'M-series', 'M3',
  'integrated', 'Apple GPU 8-core', 0,
  8, 'LPDDR5X', 256, 'NVMe',
  13.3, 'Liquid Retina', 60, 500,
  52, 1.2,
  'macOS',
  ARRAY['programming', 'business', 'general'],
  'Compact and lightweight. M3 is quick for most tasks. Great battery life for Mac lovers.',
  'Only 8GB RAM and 256GB SSD. Limited for heavy development.',
  'https://www.amazon.in/dp/B0D1SPGLRH?tag=netha-21',
  true
),

(
  'Apple MacBook Pro 14 M3 Max',
  'Apple',
  'apple-macbook-pro-14-m3-max',
  179999,
  'ARM', 'Apple', 'M-series', 'M3 Max',
  'integrated', 'Apple GPU 16-core', 0,
  24, 'LPDDR5X', 512, 'NVMe',
  14.2, 'Liquid Retina XDR', 120, 3000,
  72, 1.6,
  'macOS',
  ARRAY['video-editing', 'design', 'programming', 'ai-ml'],
  'Powerful M3 Max handles 4K video editing natively. Liquid Retina XDR is stunning. Excellent for Mac professionals.',
  'Soldered RAM not upgradeable. macOS ecosystem lock-in.',
  'https://www.amazon.in/dp/B0CZGW7FLB?tag=netha-21',
  true
),

-- STUDENT/BUDGET FRIENDLY
(
  'Realme Book Prime',
  'Realme',
  'realme-book-prime-14',
  54999,
  'x86', 'Intel', 'U', 'Core i5-11300H',
  'integrated', 'Intel Iris Xe', 0,
  8, 'LPDDR4X', 512, 'NVMe',
  14.0, 'IPS', 60, 250,
  44, 1.38,
  'Windows',
  ARRAY['general', 'students', 'programming'],
  'Lightweight and affordable. Perfect for students who need portability and long battery life.',
  'Only 8GB RAM limits multitasking. 11th gen Intel is slightly dated.',
  'https://www.amazon.in/dp/B0B5YJ4Q7N?tag=netha-21',
  true
),

(
  'ASUS Chromebook Flip C436',
  'ASUS',
  'asus-chromebook-flip-c436',
  49990,
  'x86', 'Intel', 'U', 'Core i3-1110G4',
  'integrated', 'Intel Graphics', 0,
  8, 'LPDDR4X', 256, 'eMMC',
  13.3, 'IPS', 60, 300,
  51, 1.3,
  'ChromeOS',
  ARRAY['general', 'students', 'business'],
  'Lightweight Chromebook with touchscreen. Fast and responsive for web-based work and school. Great battery life.',
  'Limited to web apps only. eMMC storage is slow. No Windows software support.',
  'https://www.amazon.in/dp/B0CRMVJGB8?tag=netha-21',
  true
);

-- Verify seeded data
SELECT COUNT(*) as total_laptops,
       COUNT(DISTINCT brand) as unique_brands,
       MIN(price_inr) as cheapest,
       MAX(price_inr) as most_expensive
FROM laptops;
