const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = 'https://mvnbzcxgbltzkxodxicr.supabase.co';
const SUPABASE_SERVICE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12bmJ6Y3hnYmx0emt4b2R4aWNyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzIyNjYyNywiZXhwIjoyMDcyODAyNjI3fQ.xtyROStQlpPwPH4KyvH7lvdDfCKbXjsie9yn_AmGlLE';

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

const laptops = [
  // ── Under ₹50,000 ────────────────────────────────────────────────────────
  {
    name: 'Acer Aspire Lite 15',
    brand: 'Acer',
    slug: 'acer-aspire-lite-15-ryzen5',
    price_inr: 35000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'AMD',
    cpu_series: 'U',
    cpu_model: 'AMD Ryzen 5 5500U',
    gpu_type: 'integrated',
    gpu_model: 'AMD Radeon Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 8,
    ram_type: 'DDR4',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 15.6,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 250,
    display_color_gamut: null,
    battery_wh: 50,
    weight_kg: 1.7,
    os_support: 'Windows',
    best_for: ['students', 'general'],
    pros:
      'The Ryzen 5 5500U delivers snappy everyday performance for browsing, documents, and light multitasking. At under ₹35,000 it includes a 512 GB NVMe drive, making storage upgrades unnecessary.',
    cons: '60 Hz IPS display and integrated graphics limit the experience for media creators or gamers.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Acer+Aspire+Lite+15+Ryzen+5+5500U&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'Lenovo IdeaPad Slim 3 15',
    brand: 'Lenovo',
    slug: 'lenovo-ideapad-slim-3-15-i3',
    price_inr: 38000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'U',
    cpu_model: 'Intel Core i3-1215U',
    gpu_type: 'integrated',
    gpu_model: 'Intel UHD Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 8,
    ram_type: 'DDR4',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 15.6,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 250,
    display_color_gamut: null,
    battery_wh: 45,
    weight_kg: 1.65,
    os_support: 'Windows',
    best_for: ['students', 'general'],
    pros:
      'Lenovo build quality and a reliable Intel Core i3-1215U make this a trustworthy choice for college work and online classes. The 512 GB NVMe SSD keeps boot and load times fast.',
    cons: 'Intel UHD integrated graphics and a dim 250-nit panel are limiting for anything beyond basic productivity.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Lenovo+IdeaPad+Slim+3+15+i3-1215U&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'HP 15s',
    brand: 'HP',
    slug: 'hp-15s-ryzen5-7520u',
    price_inr: 42000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'AMD',
    cpu_series: 'U',
    cpu_model: 'AMD Ryzen 5 7520U',
    gpu_type: 'integrated',
    gpu_model: 'AMD Radeon 610M',
    gpu_tgp_watts: 0,
    ram_gb: 8,
    ram_type: 'DDR4',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 15.6,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 250,
    display_color_gamut: null,
    battery_wh: 41,
    weight_kg: 1.69,
    os_support: 'Windows',
    best_for: ['students', 'general'],
    pros:
      'The Ryzen 5 7520U on TSMC 4 nm offers noticeably better efficiency than older-gen chips, stretching battery life on a school day. HP reliability and a full 512 GB NVMe make it a safe first laptop for students.',
    cons: 'The 41 Wh battery is small for a 15.6-inch laptop, so heavy workloads will drain it quickly.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=HP+15s+Ryzen+5+7520U+512GB&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'ASUS VivoBook 15',
    brand: 'ASUS',
    slug: 'asus-vivobook-15-i5-1235u',
    price_inr: 45000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'U',
    cpu_model: 'Intel Core i5-1235U',
    gpu_type: 'integrated',
    gpu_model: 'Intel Iris Xe Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 8,
    ram_type: 'DDR4',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 15.6,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 250,
    display_color_gamut: null,
    battery_wh: 42,
    weight_kg: 1.7,
    os_support: 'Windows',
    best_for: ['students', 'general'],
    pros:
      'Intel Iris Xe integrated graphics handle light photo editing and casual gaming better than basic Intel UHD. The Core i5-1235U has 10 cores, giving more headroom for multitasking than entry-level chips.',
    cons: 'Only 8 GB of DDR4 RAM and a 60 Hz panel hold back the experience for power users.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=ASUS+VivoBook+15+i5-1235U+512GB&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'Lenovo IdeaPad 1 14',
    brand: 'Lenovo',
    slug: 'lenovo-ideapad-1-14-ryzen3',
    price_inr: 30000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'AMD',
    cpu_series: 'U',
    cpu_model: 'AMD Ryzen 3 7320U',
    gpu_type: 'integrated',
    gpu_model: 'AMD Radeon Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 8,
    ram_type: 'LPDDR5',
    storage_gb: 256,
    storage_type: 'NVMe',
    display_size: 14.0,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 250,
    display_color_gamut: null,
    battery_wh: 38,
    weight_kg: 1.46,
    os_support: 'Windows',
    best_for: ['students', 'general'],
    pros:
      'At just 1.46 kg and ₹30,000, this is one of the most portable and affordable 14-inch laptops available, ideal for students commuting to college. LPDDR5 memory keeps the system responsive for documents, email, and video calls.',
    cons: 'The 256 GB storage fills up fast — external storage or cloud backup is a must from day one.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Lenovo+IdeaPad+1+14+Ryzen+3+7320U&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'HP Laptop 14',
    brand: 'HP',
    slug: 'hp-laptop-14-i5-1235u',
    price_inr: 47000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'U',
    cpu_model: 'Intel Core i5-1235U',
    gpu_type: 'integrated',
    gpu_model: 'Intel Iris Xe Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 8,
    ram_type: 'DDR4',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 14.0,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 250,
    display_color_gamut: null,
    battery_wh: 41,
    weight_kg: 1.46,
    os_support: 'Windows',
    best_for: ['students', 'general'],
    pros:
      'Compact 14-inch form factor with a capable Core i5-1235U makes this great for students who need portability without sacrificing processing power. Intel Iris Xe handles light creative work and video streaming smoothly.',
    cons: 'Only 8 GB DDR4 and a 60 Hz display mean it is not well suited for demanding creative tasks.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=HP+Laptop+14+i5-1235U+512GB&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },

  // ── ₹50,000–₹80,000 ──────────────────────────────────────────────────────
  {
    name: 'Lenovo IdeaPad Slim 5 15',
    brand: 'Lenovo',
    slug: 'lenovo-ideapad-slim-5-15-ryzen7',
    price_inr: 58000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'AMD',
    cpu_series: 'U',
    cpu_model: 'AMD Ryzen 7 7730U',
    gpu_type: 'integrated',
    gpu_model: 'AMD Radeon Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'DDR4',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 15.6,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 300,
    display_color_gamut: null,
    battery_wh: 56,
    weight_kg: 1.66,
    os_support: 'Windows',
    best_for: ['general', 'students', 'business'],
    pros:
      'The Ryzen 7 7730U with 16 GB RAM handles heavy browser tabs, Office suites, and light video editing without breaking a sweat. A 56 Wh battery provides all-day usage in real-world conditions.',
    cons: 'Integrated-only graphics mean no viable gaming above casual titles.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Lenovo+IdeaPad+Slim+5+15+Ryzen+7+7730U+16GB&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'ASUS VivoBook Pro 15 OLED',
    brand: 'ASUS',
    slug: 'asus-vivobook-pro-15-oled-ryzen5-6600h',
    price_inr: 65000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'AMD',
    cpu_series: 'H',
    cpu_model: 'AMD Ryzen 5 6600H',
    gpu_type: 'integrated',
    gpu_model: 'AMD Radeon 660M',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'DDR5',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 15.6,
    display_type: 'OLED',
    display_hz: 60,
    display_nits: 400,
    display_color_gamut: 100,
    battery_wh: 70,
    weight_kg: 1.65,
    os_support: 'Windows',
    best_for: ['content', 'design', 'general', 'students'],
    pros:
      'The 15.6-inch OLED panel with 100% DCI-P3 coverage delivers cinema-quality colours perfect for designers and content consumers. DDR5 memory pairs with the Ryzen 5 6600H for punchy multitasking performance.',
    cons: 'OLED panels can exhibit burn-in over time with static elements, and there is no dedicated GPU for 3D work.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=ASUS+VivoBook+Pro+15+OLED+Ryzen+5+6600H&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'Dell Inspiron 15 3530',
    brand: 'Dell',
    slug: 'dell-inspiron-15-3530-i5-1334u',
    price_inr: 62000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'U',
    cpu_model: 'Intel Core i5-1334U',
    gpu_type: 'integrated',
    gpu_model: 'Intel Iris Xe Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'DDR4',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 15.6,
    display_type: 'IPS',
    display_hz: 120,
    display_nits: 250,
    display_color_gamut: null,
    battery_wh: 54,
    weight_kg: 1.74,
    os_support: 'Windows',
    best_for: ['general', 'students', 'business'],
    pros:
      'A 120 Hz IPS display at this price tier makes scrolling and video noticeably smoother than the typical 60 Hz competition. Dell after-sales service across India is a strong reliability assurance for first-time buyers.',
    cons: 'The chassis design feels dated, and the 250-nit panel looks washed out under bright sunlight.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Dell+Inspiron+15+3530+i5-1334U+16GB&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'HP Pavilion Plus 14',
    brand: 'HP',
    slug: 'hp-pavilion-plus-14-i5-1335u',
    price_inr: 70000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'U',
    cpu_model: 'Intel Core i5-1335U',
    gpu_type: 'integrated',
    gpu_model: 'Intel Arc Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'DDR4',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 14.0,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 300,
    display_color_gamut: null,
    battery_wh: 70,
    weight_kg: 1.37,
    os_support: 'Windows',
    best_for: ['business', 'general', 'content'],
    pros:
      'Intel Arc integrated GPU handles light video editing and 1080p content creation far better than standard Iris Xe, making this a capable ultrabook for creators on a budget. The 2.2K display resolution and 70 Wh battery in a 1.37 kg chassis is excellent value.',
    cons: 'Intel Arc drivers on Windows can occasionally cause compatibility issues with older software.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=HP+Pavilion+Plus+14+i5-1335U+Intel+Arc&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'Lenovo ThinkBook 15',
    brand: 'Lenovo',
    slug: 'lenovo-thinkbook-15-i5-1335u',
    price_inr: 68000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'U',
    cpu_model: 'Intel Core i5-1335U',
    gpu_type: 'integrated',
    gpu_model: 'Intel Iris Xe Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'DDR5',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 15.6,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 300,
    display_color_gamut: null,
    battery_wh: 45,
    weight_kg: 1.7,
    os_support: 'Windows',
    best_for: ['business', 'general', 'programming'],
    pros:
      'ThinkBook series inherits ThinkPad-grade keyboard quality, making it one of the best typing experiences in this price range. DDR5 memory and a professional design make it ideal for corporate and SME use.',
    cons: 'The 45 Wh battery is notably small for the display size and will struggle to last a full workday on heavy tasks.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Lenovo+ThinkBook+15+i5-1335U+16GB+DDR5&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'Acer Swift Go 14',
    brand: 'Acer',
    slug: 'acer-swift-go-14-ryzen5-7530u',
    price_inr: 55000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'AMD',
    cpu_series: 'U',
    cpu_model: 'AMD Ryzen 5 7530U',
    gpu_type: 'integrated',
    gpu_model: 'AMD Radeon Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'LPDDR5',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 14.0,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 300,
    display_color_gamut: null,
    battery_wh: 65,
    weight_kg: 1.25,
    os_support: 'Windows',
    best_for: ['business', 'general', 'students'],
    pros:
      'At just 1.25 kg with a 65 Wh battery, the Swift Go 14 is one of the lightest and longest-lasting laptops under ₹60,000. LPDDR5 memory and the Ryzen 5 7530U keep productivity tasks feeling snappy all day.',
    cons: 'The 60 Hz IPS display and no dedicated GPU limit appeal for creators who need colour accuracy or GPU acceleration.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Acer+Swift+Go+14+Ryzen+5+7530U+16GB&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'MI Notebook Pro 120G',
    brand: 'MI',
    slug: 'mi-notebook-pro-120g-i5-12500h',
    price_inr: 60000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'H',
    cpu_model: 'Intel Core i5-12500H',
    gpu_type: 'integrated',
    gpu_model: 'Intel Iris Xe Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'DDR5',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 15.6,
    display_type: 'IPS',
    display_hz: 120,
    display_nits: 300,
    display_color_gamut: null,
    battery_wh: 72,
    weight_kg: 1.8,
    os_support: 'Windows',
    best_for: ['general', 'programming', 'students'],
    pros:
      'The Core i5-12500H is a full H-class chip delivering desktop-like multi-core performance that outclasses U-series rivals at this price. A 120 Hz display and 72 Wh battery add premium usability at a mid-range price.',
    cons: 'At 1.8 kg it is heavier than ultrabook competition, and Xiaomi after-sales service network in India is more limited than HP or Dell.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=MI+Notebook+Pro+120G+i5-12500H+16GB&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'HP Envy x360 13',
    brand: 'HP',
    slug: 'hp-envy-x360-13-ryzen5-7530u',
    price_inr: 75000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'AMD',
    cpu_series: 'U',
    cpu_model: 'AMD Ryzen 5 7530U',
    gpu_type: 'integrated',
    gpu_model: 'AMD Radeon Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'DDR4',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 13.3,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 400,
    display_color_gamut: null,
    battery_wh: 51,
    weight_kg: 1.27,
    os_support: 'Windows',
    best_for: ['business', 'general', 'content'],
    pros:
      'The 2-in-1 360-degree hinge and 400-nit touchscreen make it versatile for presentations, note-taking with a stylus, and content consumption in tent mode. At 1.27 kg it is easy to carry between meetings all day.',
    cons: 'The 51 Wh battery is on the smaller side for a premium ultrabook, limiting heavy-use runtime.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=HP+Envy+x360+13+Ryzen+5+7530U+16GB&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },

  // ── ₹80,000–₹1,20,000 ────────────────────────────────────────────────────
  {
    name: 'ASUS VivoBook Pro 15 OLED K6500',
    brand: 'ASUS',
    slug: 'asus-vivobook-pro-15-oled-k6500-rtx4050',
    price_inr: 95000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'AMD',
    cpu_series: 'HX',
    cpu_model: 'AMD Ryzen 7 7745HX',
    gpu_type: 'dedicated',
    gpu_model: 'NVIDIA GeForce RTX 4050',
    gpu_tgp_watts: 50,
    ram_gb: 16,
    ram_type: 'DDR5',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 15.6,
    display_type: 'OLED',
    display_hz: 120,
    display_nits: 600,
    display_color_gamut: 100,
    battery_wh: 70,
    weight_kg: 1.65,
    os_support: 'Windows',
    best_for: ['design', 'content', 'video-editing', 'programming', 'gaming'],
    pros:
      'The 120 Hz OLED panel with 600 nits and 100% DCI-P3 is among the best displays at this price, perfect for video editors and graphic designers. The RTX 4050 with DLSS 3 support enables smooth 1080p gaming and GPU-accelerated creative workflows.',
    cons: 'Only 512 GB storage fills up quickly for creative professionals handling large media files.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=ASUS+VivoBook+Pro+15+OLED+K6500+RTX+4050+Ryzen+7&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'Dell XPS 13 9340',
    brand: 'Dell',
    slug: 'dell-xps-13-9340-ultra5-125h',
    price_inr: 110000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'H',
    cpu_model: 'Intel Core Ultra 5 125H',
    gpu_type: 'integrated',
    gpu_model: 'Intel Arc Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'LPDDR5X',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 13.4,
    display_type: 'IPS',
    display_hz: 120,
    display_nits: 400,
    display_color_gamut: null,
    battery_wh: 55,
    weight_kg: 1.17,
    os_support: 'Windows',
    best_for: ['business', 'programming', 'general'],
    pros:
      'At 1.17 kg the XPS 13 is one of the lightest premium Windows ultrabooks available, making it ideal for frequent travellers and executives. Intel Core Ultra 5 with a dedicated NPU handles AI-accelerated tasks natively on Windows.',
    cons: 'No dedicated GPU, a non-upgradeable LPDDR5X RAM, and premium pricing leave little room for creative workloads.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Dell+XPS+13+9340+Core+Ultra+5+125H&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'HP Spectre x360 14',
    brand: 'HP',
    slug: 'hp-spectre-x360-14-i7-1355u',
    price_inr: 105000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'U',
    cpu_model: 'Intel Core i7-1355U',
    gpu_type: 'integrated',
    gpu_model: 'Intel Iris Xe Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'LPDDR5',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 13.5,
    display_type: 'OLED',
    display_hz: 60,
    display_nits: 400,
    display_color_gamut: 100,
    battery_wh: 66,
    weight_kg: 1.36,
    os_support: 'Windows',
    best_for: ['business', 'content', 'design', 'general'],
    pros:
      'The 13.5-inch 3:2 OLED touchscreen gives more vertical workspace for documents and creative tools than standard 16:9 laptops. Premium CNC-aluminium build and gem-cut design make this the most visually distinctive Windows laptop at this price.',
    cons: 'The Core i7-1355U is a 15W chip, so sustained workloads can feel slower than H-class alternatives at the same price.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=HP+Spectre+x360+14+i7-1355U+OLED&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'Lenovo Slim Pro 7',
    brand: 'Lenovo',
    slug: 'lenovo-slim-pro-7-ryzen7-7745hx',
    price_inr: 85000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'AMD',
    cpu_series: 'HX',
    cpu_model: 'AMD Ryzen 7 7745HX',
    gpu_type: 'integrated',
    gpu_model: 'AMD Radeon 780M',
    gpu_tgp_watts: 0,
    ram_gb: 32,
    ram_type: 'DDR5',
    storage_gb: 1024,
    storage_type: 'NVMe',
    display_size: 14.5,
    display_type: 'IPS',
    display_hz: 144,
    display_nits: 400,
    display_color_gamut: null,
    battery_wh: 75,
    weight_kg: 1.49,
    os_support: 'Windows',
    best_for: ['programming', 'business', 'general', 'ai-ml'],
    pros:
      '32 GB DDR5 and a 1 TB NVMe drive in a 1.49 kg chassis at under ₹90,000 offers exceptional value for developers and data analysts. The 144 Hz IPS display and Radeon 780M iGPU handle light gaming and smooth UI interactions.',
    cons: 'No dedicated GPU limits 3D rendering and serious gaming despite the powerful CPU.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Lenovo+Slim+Pro+7+Ryzen+7+7745HX+32GB&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'ASUS ROG Zephyrus G14 2024',
    brand: 'ASUS',
    slug: 'asus-rog-zephyrus-g14-2024',
    price_inr: 115000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'AMD',
    cpu_series: 'H',
    cpu_model: 'AMD Ryzen 9 7940HS',
    gpu_type: 'dedicated',
    gpu_model: 'NVIDIA GeForce RTX 4060',
    gpu_tgp_watts: 80,
    ram_gb: 16,
    ram_type: 'DDR5',
    storage_gb: 1024,
    storage_type: 'NVMe',
    display_size: 14.0,
    display_type: 'IPS',
    display_hz: 165,
    display_nits: 500,
    display_color_gamut: null,
    battery_wh: 73,
    weight_kg: 1.65,
    os_support: 'Windows',
    best_for: ['gaming', 'content', 'programming', 'video-editing'],
    pros:
      'The RTX 4060 at 80W TGP in a 1.65 kg chassis delivers exceptional gaming and creative performance that rivals heavier gaming laptops. The 165 Hz IPS display at 500 nits is bright and smooth enough for both gaming and content creation.',
    cons: 'Only 16 GB of DDR5 RAM can bottleneck memory-intensive workflows like video editing with heavy effects.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=ASUS+ROG+Zephyrus+G14+Ryzen+9+7940HS+RTX+4060&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'MSI Modern 14',
    brand: 'MSI',
    slug: 'msi-modern-14-i7-1355u',
    price_inr: 82000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'U',
    cpu_model: 'Intel Core i7-1355U',
    gpu_type: 'integrated',
    gpu_model: 'Intel Iris Xe Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'DDR4',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 14.0,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 300,
    display_color_gamut: null,
    battery_wh: 52,
    weight_kg: 1.4,
    os_support: 'Windows',
    best_for: ['business', 'general', 'programming'],
    pros:
      'Slim, professional design at 1.4 kg with a Core i7-1355U making it fast enough for development work, spreadsheets, and multitasking. MSI laptop keyboards offer excellent tactile feedback appreciated by writers and programmers.',
    cons: 'The 52 Wh battery and 60 Hz display feel underwhelming relative to the ₹82,000 asking price.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=MSI+Modern+14+i7-1355U+16GB&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'Lenovo IdeaPad Gaming 3',
    brand: 'Lenovo',
    slug: 'lenovo-ideapad-gaming-3-rtx4050',
    price_inr: 80000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'AMD',
    cpu_series: 'HX',
    cpu_model: 'AMD Ryzen 5 7535HX',
    gpu_type: 'dedicated',
    gpu_model: 'NVIDIA GeForce RTX 4050',
    gpu_tgp_watts: 60,
    ram_gb: 16,
    ram_type: 'DDR5',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 15.6,
    display_type: 'IPS',
    display_hz: 144,
    display_nits: 300,
    display_color_gamut: null,
    battery_wh: 45,
    weight_kg: 2.3,
    os_support: 'Windows',
    best_for: ['gaming', 'general', 'students'],
    pros:
      'The RTX 4050 at 60W combined with 144 Hz IPS lets you play most modern AAA titles at 1080p medium-high settings comfortably. This is among the most affordable dedicated-GPU gaming laptops in India with DLSS 3 support.',
    cons: 'At 2.3 kg with only a 45 Wh battery, it is heavy and tethered to an outlet during intense gaming sessions.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Lenovo+IdeaPad+Gaming+3+Ryzen+5+7535HX+RTX+4050&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },

  // ── ₹1,20,000–₹2,00,000 ──────────────────────────────────────────────────
  {
    name: 'Apple MacBook Air M3 13',
    brand: 'Apple',
    slug: 'apple-macbook-air-m3-13',
    price_inr: 130000,
    price_usd: null,
    cpu_arch: 'ARM',
    cpu_brand: 'Apple',
    cpu_series: 'M-series',
    cpu_model: 'Apple M3 8-core CPU',
    gpu_type: 'integrated',
    gpu_model: 'Apple M3 10-core GPU',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'LPDDR5X',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 13.6,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 500,
    display_color_gamut: 100,
    battery_wh: 52,
    weight_kg: 1.24,
    os_support: 'macOS',
    best_for: ['design', 'content', 'programming', 'general', 'business'],
    pros:
      'Apple M3 delivers class-leading performance-per-watt, enabling all-day battery life with no fan noise for sustained workloads. The Liquid Retina display with 500 nits and P3 wide colour is exceptional for designers and content creators.',
    cons: 'Only a 60 Hz display and limited to 24 GB unified RAM maximum can be constraining for heavy Pro workflows.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Apple+MacBook+Air+M3+13+inch+16GB+512GB&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'Dell XPS 15 9530',
    brand: 'Dell',
    slug: 'dell-xps-15-9530-rtx4060',
    price_inr: 175000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'H',
    cpu_model: 'Intel Core i7-13700H',
    gpu_type: 'dedicated',
    gpu_model: 'NVIDIA GeForce RTX 4060',
    gpu_tgp_watts: 80,
    ram_gb: 16,
    ram_type: 'DDR5',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 15.6,
    display_type: 'OLED',
    display_hz: 60,
    display_nits: 400,
    display_color_gamut: 100,
    battery_wh: 86,
    weight_kg: 1.86,
    os_support: 'Windows',
    best_for: ['design', 'video-editing', 'content', 'programming'],
    pros:
      'The 15.6-inch OLED with 100% DCI-P3 and RTX 4060 at 80W is a dream combination for video editors and 3D designers who need accurate colour and GPU acceleration. The 86 Wh battery and premium aluminium build make it a polished, durable workstation.',
    cons: 'Only 512 GB storage and 16 GB RAM at ₹1,75,000 feels ungenerous — expect to spend more for upgrades.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Dell+XPS+15+9530+i7-13700H+RTX+4060+OLED&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'Apple MacBook Air M3 15',
    brand: 'Apple',
    slug: 'apple-macbook-air-m3-15',
    price_inr: 155000,
    price_usd: null,
    cpu_arch: 'ARM',
    cpu_brand: 'Apple',
    cpu_series: 'M-series',
    cpu_model: 'Apple M3 8-core CPU',
    gpu_type: 'integrated',
    gpu_model: 'Apple M3 10-core GPU',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'LPDDR5X',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 15.3,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 500,
    display_color_gamut: 100,
    battery_wh: 66,
    weight_kg: 1.51,
    os_support: 'macOS',
    best_for: ['design', 'content', 'programming', 'general', 'business'],
    pros:
      'The 15.3-inch Liquid Retina display gives significantly more screen real estate than the 13-inch model while keeping the fanless M3 efficiency and a 66 Wh battery that lasts 15+ hours. It is the best big-screen ultrabook for creative professionals who travel.',
    cons: 'The 60 Hz panel and no ProMotion is a notable compromise versus the MacBook Pro at a similar price point.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Apple+MacBook+Air+M3+15+inch+16GB+512GB&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'ASUS ProArt Studiobook 16',
    brand: 'ASUS',
    slug: 'asus-proart-studiobook-16-rtx4070',
    price_inr: 180000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'HX',
    cpu_model: 'Intel Core i9-13980HX',
    gpu_type: 'dedicated',
    gpu_model: 'NVIDIA GeForce RTX 4070',
    gpu_tgp_watts: 80,
    ram_gb: 32,
    ram_type: 'DDR5',
    storage_gb: 1024,
    storage_type: 'NVMe',
    display_size: 16.0,
    display_type: 'OLED',
    display_hz: 120,
    display_nits: 550,
    display_color_gamut: 100,
    battery_wh: 90,
    weight_kg: 2.4,
    os_support: 'Windows',
    best_for: ['design', 'video-editing', 'ai-ml', 'content', '3d-rendering'],
    pros:
      'The 16-inch 120 Hz OLED at 100% DCI-P3 with factory calibration and the RTX 4070 make this the definitive creator workstation under ₹2 lakh. ASUS ProArt includes Pantone Validated colour accuracy ideal for print and video professionals.',
    cons: 'At 2.4 kg it is not a portable laptop — best suited as a desktop replacement.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=ASUS+ProArt+Studiobook+16+i9-13980HX+RTX+4070+OLED&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'Lenovo ThinkPad X1 Carbon Gen 11',
    brand: 'Lenovo',
    slug: 'lenovo-thinkpad-x1-carbon-gen11',
    price_inr: 145000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'U',
    cpu_model: 'Intel Core i7-1365U',
    gpu_type: 'integrated',
    gpu_model: 'Intel Iris Xe Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'LPDDR5',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 14.0,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 400,
    display_color_gamut: null,
    battery_wh: 57,
    weight_kg: 1.12,
    os_support: 'Windows',
    best_for: ['business', 'programming', 'general'],
    pros:
      'At 1.12 kg the X1 Carbon is one of the lightest 14-inch business laptops on the market, certified for MIL-STD-810H durability. The legendary ThinkPad keyboard and enterprise-grade security features (fingerprint + IR camera) justify the premium for corporate users.',
    cons: 'No dedicated GPU and a 60 Hz panel at ₹1,45,000 is hard to justify for anyone outside enterprise or business travel use cases.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Lenovo+ThinkPad+X1+Carbon+Gen+11+i7-1365U&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },

  // ── Above ₹2,00,000 ───────────────────────────────────────────────────────
  {
    name: 'Apple MacBook Pro M3 Pro 14',
    brand: 'Apple',
    slug: 'apple-macbook-pro-m3-pro-14',
    price_inr: 210000,
    price_usd: null,
    cpu_arch: 'ARM',
    cpu_brand: 'Apple',
    cpu_series: 'M-series',
    cpu_model: 'Apple M3 Pro 11-core CPU',
    gpu_type: 'integrated',
    gpu_model: 'Apple M3 Pro 14-core GPU',
    gpu_tgp_watts: 0,
    ram_gb: 18,
    ram_type: 'LPDDR5X',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 14.2,
    display_type: 'Mini-LED',
    display_hz: 120,
    display_nits: 1000,
    display_color_gamut: 100,
    battery_wh: 70,
    weight_kg: 1.61,
    os_support: 'macOS',
    best_for: ['design', 'video-editing', 'programming', 'content', 'ai-ml'],
    pros:
      'The 14.2-inch Liquid Retina XDR Mini-LED display hits 1000 nits sustained brightness with true blacks, making it the best laptop display for colour-critical creative work. The M3 Pro chip handles Final Cut Pro, Xcode, and ML inference tasks with unmatched efficiency and silence.',
    cons: 'Starting price at ₹2,10,000 for only 18 GB RAM and 512 GB storage is expensive — heavy Pro users will need to pay significantly more for adequate storage.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Apple+MacBook+Pro+M3+Pro+14+inch+18GB&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'Apple MacBook Pro M3 Pro 16',
    brand: 'Apple',
    slug: 'apple-macbook-pro-m3-pro-16',
    price_inr: 280000,
    price_usd: null,
    cpu_arch: 'ARM',
    cpu_brand: 'Apple',
    cpu_series: 'M-series',
    cpu_model: 'Apple M3 Pro 12-core CPU',
    gpu_type: 'integrated',
    gpu_model: 'Apple M3 Pro 18-core GPU',
    gpu_tgp_watts: 0,
    ram_gb: 36,
    ram_type: 'LPDDR5X',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 16.2,
    display_type: 'Mini-LED',
    display_hz: 120,
    display_nits: 1000,
    display_color_gamut: 100,
    battery_wh: 100,
    weight_kg: 2.14,
    os_support: 'macOS',
    best_for: ['design', 'video-editing', 'programming', 'content', 'ai-ml'],
    pros:
      'The 16-inch Liquid Retina XDR Mini-LED with ProMotion 120 Hz and 100 Wh battery delivers up to 22 hours of real-world use — ideal for long editing sessions away from a desk. 36 GB unified memory makes it the top choice for 4K/8K video editors and ML engineers.',
    cons: 'At ₹2,80,000 the base model still ships with only 512 GB SSD, which is insufficient for media-heavy workflows without external drives.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Apple+MacBook+Pro+M3+Pro+16+inch+36GB&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'ASUS ROG Zephyrus Duo 16',
    brand: 'ASUS',
    slug: 'asus-rog-zephyrus-duo-16-rtx4090',
    price_inr: 350000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'AMD',
    cpu_series: 'HX',
    cpu_model: 'AMD Ryzen 9 7945HX',
    gpu_type: 'dedicated',
    gpu_model: 'NVIDIA GeForce RTX 4090',
    gpu_tgp_watts: 80,
    ram_gb: 32,
    ram_type: 'DDR5',
    storage_gb: 2048,
    storage_type: 'NVMe',
    display_size: 16.0,
    display_type: 'Mini-LED',
    display_hz: 240,
    display_nits: 1100,
    display_color_gamut: 100,
    battery_wh: 90,
    weight_kg: 2.38,
    os_support: 'Windows',
    best_for: ['gaming', 'video-editing', 'ai-ml', 'design', 'content'],
    pros:
      'The RTX 4090 with a secondary ScreenPad Plus display makes this the most powerful and versatile laptop available, enabling 4K game streaming, 3D rendering, and AI workloads simultaneously. The 240 Hz Mini-LED display at 1100 nits is the best gaming display on any laptop.',
    cons: 'At 2.38 kg and limited to 80W TGP the RTX 4090 cannot match a desktop GPU, and the ₹3,50,000 price leaves little room for compromise.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=ASUS+ROG+Zephyrus+Duo+16+Ryzen+9+7945HX+RTX+4090&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'Razer Blade 16',
    brand: 'Razer',
    slug: 'razer-blade-16-rtx4090',
    price_inr: 320000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'HX',
    cpu_model: 'Intel Core i9-14900HX',
    gpu_type: 'dedicated',
    gpu_model: 'NVIDIA GeForce RTX 4090',
    gpu_tgp_watts: 100,
    ram_gb: 32,
    ram_type: 'DDR5',
    storage_gb: 2048,
    storage_type: 'NVMe',
    display_size: 16.0,
    display_type: 'OLED',
    display_hz: 240,
    display_nits: 600,
    display_color_gamut: 100,
    battery_wh: 95,
    weight_kg: 2.1,
    os_support: 'Windows',
    best_for: ['gaming', 'video-editing', 'content', 'design'],
    pros:
      'The RTX 4090 at a best-in-class 100W TGP combined with a 240 Hz OLED display makes the Razer Blade 16 the ultimate gaming laptop for those who refuse to compromise on either display quality or raw GPU power. Razer CNC aluminium build quality is as premium as any laptop on the market.',
    cons: 'At ₹3,20,000 Razer charges a significant premium for brand and design over competitors with similar specs.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Razer+Blade+16+i9-14900HX+RTX+4090+OLED&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },

  // ── Linux Laptops ────────────────────────────────────────────────────────
  {
    name: 'Lenovo ThinkPad E14',
    brand: 'Lenovo',
    slug: 'lenovo-thinkpad-e14-ryzen5-7530u-linux',
    price_inr: 52000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'AMD',
    cpu_series: 'U',
    cpu_model: 'AMD Ryzen 5 7530U',
    gpu_type: 'integrated',
    gpu_model: 'AMD Radeon Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'DDR4',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 14.0,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 300,
    display_color_gamut: null,
    battery_wh: 52,
    weight_kg: 1.46,
    os_support: 'Linux',
    best_for: ['programming', 'business', 'students', 'general'],
    pros:
      'ThinkPad legendary keyboard and durability combined with excellent Linux driver support (community-tested on Ubuntu, Fedora, Debian). Ryzen 5 7530U with 16GB RAM handles development, compiling, and DevOps tools without fan noise.',
    cons: 'Only 60 Hz IPS display and integrated graphics limit media creation and gaming compared to premium Linux alternatives.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Lenovo+ThinkPad+E14+Ryzen+5+7530U+16GB&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'Framework Laptop 13 Inch',
    brand: 'Framework',
    slug: 'framework-laptop-13-ryzen5-7640u-linux',
    price_inr: 95000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'AMD',
    cpu_series: 'U',
    cpu_model: 'AMD Ryzen 5 7640U',
    gpu_type: 'integrated',
    gpu_model: 'AMD Radeon Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'LPDDR5X',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 13.3,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 400,
    display_color_gamut: null,
    battery_wh: 55,
    weight_kg: 1.3,
    os_support: 'Linux',
    best_for: ['programming', 'business', 'general', 'students'],
    pros:
      'Open-source hardware design with modular expansion cards (USB-C, HDMI, DP) and user-replaceable parts make this the Linux enthusiast dream machine. Native Linux support with pre-configured Ubuntu or Fedora. Ryzen 5 7640U and LPDDR5X memory handle all development tasks efficiently.',
    cons: '60 Hz display and no dedicated GPU limit video editing and gaming despite premium positioning.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Framework+Laptop+13+Ryzen+5+7640U&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'System76 Lemur Pro 10',
    brand: 'System76',
    slug: 'system76-lemur-pro-10-i7-1365u-linux',
    price_inr: 105000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'U',
    cpu_model: 'Intel Core i7-1365U',
    gpu_type: 'integrated',
    gpu_model: 'Intel Iris Xe Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'DDR5',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 14.1,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 300,
    display_color_gamut: null,
    battery_wh: 51,
    weight_kg: 1.33,
    os_support: 'Linux',
    best_for: ['programming', 'business', 'general'],
    pros:
      'System76 ships with Pop!_OS (Ubuntu-based) pre-installed and optimised for Linux workflow. They provide lifetime hardware support and contribute extensively to the Linux ecosystem. Core i7-1365U with DDR5 ensures smooth development and system administration work.',
    cons: 'Premium pricing for a Linux-only vendor and limited service availability outside North America may be a concern for Indian buyers.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=System76+Lemur+Pro+i7-1365U&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'Lenovo ThinkPad X1 Carbon Gen 11 Linux',
    brand: 'Lenovo',
    slug: 'lenovo-thinkpad-x1-carbon-gen11-linux',
    price_inr: 140000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'U',
    cpu_model: 'Intel Core i7-1365U',
    gpu_type: 'integrated',
    gpu_model: 'Intel Iris Xe Graphics',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'LPDDR5',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 14.0,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 400,
    display_color_gamut: null,
    battery_wh: 57,
    weight_kg: 1.12,
    os_support: 'Linux',
    best_for: ['business', 'programming', 'general'],
    pros:
      'ThinkPad X1 Carbon with certified Linux support delivers enterprise-grade build quality, keyboard, and BIOS/firmware support for Linux environments. 1.12 kg ultraportable with MIL-STD-810H durability and native Linux driver support (RHEL/Ubuntu certified).',
    cons: '60 Hz display and integrated GPU at ₹1,40,000 is expensive compared to equivalently specced Windows alternatives; primarily targets corporate Linux deployments.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Lenovo+ThinkPad+X1+Carbon+Gen+11+i7-1365U&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'ASUS VivoBook Pro 15 Linux',
    brand: 'ASUS',
    slug: 'asus-vivobook-pro-15-oled-linux-ryzen5',
    price_inr: 68000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'AMD',
    cpu_series: 'H',
    cpu_model: 'AMD Ryzen 5 6600H',
    gpu_type: 'integrated',
    gpu_model: 'AMD Radeon 660M',
    gpu_tgp_watts: 0,
    ram_gb: 16,
    ram_type: 'DDR5',
    storage_gb: 512,
    storage_type: 'NVMe',
    display_size: 15.6,
    display_type: 'OLED',
    display_hz: 60,
    display_nits: 400,
    display_color_gamut: 100,
    battery_wh: 70,
    weight_kg: 1.65,
    os_support: 'Linux',
    best_for: ['content', 'design', 'programming', 'students', 'general'],
    pros:
      'ASUS OLED display with 100% DCI-P3 coverage and excellent Linux driver support (AMD open-source AMDGPU stack) make this ideal for Linux content creators. Ryzen 5 6600H with DDR5 and good thermal design handles compilation and media tasks smoothly.',
    cons: 'No dedicated GPU limits 3D rendering; OLED can suffer from burn-in on static UI elements in long development sessions.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=ASUS+VivoBook+Pro+15+OLED+Ryzen+5+6600H&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
  {
    name: 'Lenovo ThinkPad P16 Linux Workstation',
    brand: 'Lenovo',
    slug: 'lenovo-thinkpad-p16-linux-rtx5880ada',
    price_inr: 280000,
    price_usd: null,
    cpu_arch: 'x86',
    cpu_brand: 'Intel',
    cpu_series: 'HX',
    cpu_model: 'Intel Core i9-13900HX',
    gpu_type: 'dedicated',
    gpu_model: 'NVIDIA RTX 5880 Ada',
    gpu_tgp_watts: 80,
    ram_gb: 64,
    ram_type: 'DDR5',
    storage_gb: 1024,
    storage_type: 'NVMe',
    display_size: 16.0,
    display_type: 'IPS',
    display_hz: 60,
    display_nits: 500,
    display_color_gamut: null,
    battery_wh: 87,
    weight_kg: 2.38,
    os_support: 'Linux',
    best_for: ['ai-ml', 'video-editing', 'programming', 'design', '3d-rendering'],
    pros:
      'ThinkPad P16 with professional RTX Ada GPU and 64GB DDR5 is built for Linux AI/ML engineers and VFX artists. Full ISV certification for Ubuntu, RHEL, and CentOS with dedicated NVIDIA CUDA driver support ensures rock-solid Linux workstation reliability.',
    cons: 'At 2.38 kg and ₹2,80,000, this is a desktop replacement workstation, not a portable ultrabook. Overkill for web development unless doing heavy GPU-accelerated work.',
    affiliate_amazon_in:
      'https://www.amazon.in/s?k=Lenovo+ThinkPad+P16+i9-13900HX+RTX+5880&tag=netha-21',
    affiliate_amazon_com: null,
    image_url: null,
    is_active: true,
  },
];

async function seed() {
  console.log(`Seeding ${laptops.length} laptops in batches of 10...\n`);

  const batchSize = 10;
  for (let i = 0; i < laptops.length; i += batchSize) {
    const batch = laptops.slice(i, i + batchSize);
    const batchNum = Math.floor(i / batchSize) + 1;

    const { data, error } = await supabase.from('laptops').insert(batch).select('id, name');

    if (error) {
      console.error(`Batch ${batchNum} FAILED:`, error.message);
      console.error('Details:', JSON.stringify(error, null, 2));
    } else {
      console.log(`Batch ${batchNum} SUCCESS — inserted ${data.length} rows:`);
      data.forEach((row) => console.log(`  [${row.id}] ${row.name}`));
    }
    console.log();
  }

  console.log('Seeding complete.');
}

seed().catch((err) => {
  console.error('Unexpected error:', err);
  process.exit(1);
});
